// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infrastructure;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20260918164447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_email");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Email = "olena.kovalenko@example.com",
                            FullName = "Олена Коваленко",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "bohdan.shevchenko@example.com",
                            FullName = "Богдан Шевченко",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Email = "oksana.melnyk@example.com",
                            FullName = "Оксана Мельник",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_tasks_creator_id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_tasks_due_at");

                    b.HasIndex("AssigneeId", "Status")
                        .HasDatabaseName("ix_tasks_assignee_id_status");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_br1_completed_at_iff_completed", "(status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_tasks_br2_due_at_not_before_planned_start_at", "planned_start_at IS NULL OR due_at IS NULL OR due_at >= planned_start_at");

                            t.HasCheckConstraint("ck_tasks_br5_assignee_not_creator", "assignee_id <> creator_id");

                            t.HasCheckConstraint("ck_tasks_status_valid", "status IN ('New', 'InProgress', 'Completed', 'Cancelled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            DueAt = new DateTimeOffset(new DateTime(2026, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PlannedStartAt = new DateTimeOffset(new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "New",
                            Title = "Підготувати квартальний звіт з продажів"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DueAt = new DateTimeOffset(new DateTime(2026, 9, 5, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PlannedStartAt = new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Completed",
                            Title = "Передзвонити ключовому клієнту"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AssigneeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = "Cancelled",
                            Title = "Очистити дублікати контактів"
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_employees_assignee_id");

                    b.HasOne("TaskManagement.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_employees_creator_id");
                });
#pragma warning restore 612, 618
        }
    }
}
