// InitialCreate: schema changes (generated by dotnet ef 10.0.12; the trigger SQL is added by hand, spec §11).
//
// Tables and columns
//   employees: id uuid NOT NULL, full_name character varying(200) NOT NULL, email character varying(254) NOT NULL,
//              is_active boolean NOT NULL
//   tasks:     id uuid NOT NULL, title character varying(200) NOT NULL, status character varying(20) NOT NULL,
//              creator_id uuid NOT NULL, assignee_id uuid NOT NULL, planned_start_at timestamptz NULL,
//              due_at timestamptz NULL, completed_at timestamptz NULL
//              (plus xmin xid: PostgreSQL system column, the concurrency token; listed by EF, not created)
// Primary keys
//   pk_employees (employees.id), pk_tasks (tasks.id)
// Foreign keys
//   fk_tasks_employees_creator_id  tasks(creator_id)  -> employees(id) ON DELETE RESTRICT
//   fk_tasks_employees_assignee_id tasks(assignee_id) -> employees(id) ON DELETE RESTRICT
// Indexes
//   ux_employees_email          employees(email) UNIQUE
//   ix_tasks_assignee_id_status tasks(assignee_id, status)
//   ix_tasks_due_at             tasks(due_at)
//   ix_tasks_creator_id         tasks(creator_id)
// CHECK constraints (tasks)
//   ck_tasks_status_valid                           status IN ('New', 'InProgress', 'Completed', 'Cancelled')
//   ck_tasks_br1_completed_at_iff_completed         BR1: completed_at set iff status = 'Completed'
//   ck_tasks_br2_due_at_not_before_planned_start_at BR2: due_at >= planned_start_at when both are set
//   ck_tasks_br5_assignee_not_creator               BR5: assignee_id <> creator_id
// Trigger (raw SQL at the end of Up(), dropped at the start of Down())
//   function tasks_enforce_br3_br4() (plpgsql)
//   trigger trg_tasks_br3_br4 BEFORE INSERT OR UPDATE OF status ON tasks FOR EACH ROW
//     BR3: on insert, an inactive assignee raises 23514 / trg_tasks_br3_assignee_active
//     BR4: a status change out of Completed or Cancelled raises 23514 / trg_tasks_br4_final_status
// Seed rows (demo data)
//   employees: 10000000-…-0001 Alice Morgan (active), 10000000-…-0002 Bob Chen (active),
//              10000000-…-0003 Carol Diaz (inactive)
//   tasks:     20000000-…-0001 'Prepare Q4 sales report' New, Alice -> Bob
//              20000000-…-0002 'Call back key account' Completed, Bob -> Alice
//              20000000-…-0003 'Clean up duplicate contacts' Cancelled, Alice -> Bob
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace TaskManagement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "employees",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    full_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    email = table.Column<string>(type: "character varying(254)", maxLength: 254, nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_employees", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "tasks",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    creator_id = table.Column<Guid>(type: "uuid", nullable: false),
                    assignee_id = table.Column<Guid>(type: "uuid", nullable: false),
                    planned_start_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    due_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    completed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tasks", x => x.id);
                    table.CheckConstraint("ck_tasks_br1_completed_at_iff_completed", "(status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)");
                    table.CheckConstraint("ck_tasks_br2_due_at_not_before_planned_start_at", "planned_start_at IS NULL OR due_at IS NULL OR due_at >= planned_start_at");
                    table.CheckConstraint("ck_tasks_br5_assignee_not_creator", "assignee_id <> creator_id");
                    table.CheckConstraint("ck_tasks_status_valid", "status IN ('New', 'InProgress', 'Completed', 'Cancelled')");
                    table.ForeignKey(
                        name: "fk_tasks_employees_assignee_id",
                        column: x => x.assignee_id,
                        principalTable: "employees",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_tasks_employees_creator_id",
                        column: x => x.creator_id,
                        principalTable: "employees",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "employees",
                columns: new[] { "id", "email", "full_name", "is_active" },
                values: new object[,]
                {
                    { new Guid("10000000-0000-0000-0000-000000000001"), "alice.morgan@example.com", "Alice Morgan", true },
                    { new Guid("10000000-0000-0000-0000-000000000002"), "bob.chen@example.com", "Bob Chen", true },
                    { new Guid("10000000-0000-0000-0000-000000000003"), "carol.diaz@example.com", "Carol Diaz", false }
                });

            migrationBuilder.InsertData(
                table: "tasks",
                columns: new[] { "id", "assignee_id", "completed_at", "creator_id", "due_at", "planned_start_at", "status", "title" },
                values: new object[,]
                {
                    { new Guid("20000000-0000-0000-0000-000000000001"), new Guid("10000000-0000-0000-0000-000000000002"), null, new Guid("10000000-0000-0000-0000-000000000001"), new DateTimeOffset(new DateTime(2026, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), new DateTimeOffset(new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "New", "Prepare Q4 sales report" },
                    { new Guid("20000000-0000-0000-0000-000000000002"), new Guid("10000000-0000-0000-0000-000000000001"), new DateTimeOffset(new DateTime(2026, 9, 4, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), new Guid("10000000-0000-0000-0000-000000000002"), new DateTimeOffset(new DateTime(2026, 9, 5, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), new DateTimeOffset(new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "Completed", "Call back key account" },
                    { new Guid("20000000-0000-0000-0000-000000000003"), new Guid("10000000-0000-0000-0000-000000000002"), null, new Guid("10000000-0000-0000-0000-000000000001"), null, null, "Cancelled", "Clean up duplicate contacts" }
                });

            migrationBuilder.CreateIndex(
                name: "ux_employees_email",
                table: "employees",
                column: "email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_tasks_assignee_id_status",
                table: "tasks",
                columns: new[] { "assignee_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_tasks_creator_id",
                table: "tasks",
                column: "creator_id");

            migrationBuilder.CreateIndex(
                name: "ix_tasks_due_at",
                table: "tasks",
                column: "due_at");

            // BR3 and BR4: EF Core does not create triggers from the model (spec §11, ADR 0009).
            migrationBuilder.Sql("""
                CREATE FUNCTION tasks_enforce_br3_br4() RETURNS trigger
                LANGUAGE plpgsql AS $$
                DECLARE
                    assignee_active boolean;
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        -- BR3: the assignee must be active. FOR SHARE blocks a concurrent deactivation until this transaction ends.
                        -- An unknown assignee leaves assignee_active NULL, so the FK reports it (23503), not BR3.
                        SELECT is_active INTO assignee_active FROM employees WHERE id = NEW.assignee_id FOR SHARE;
                        IF assignee_active IS FALSE THEN
                            RAISE EXCEPTION 'BR3: employee % is inactive and cannot be given a new task.', NEW.assignee_id
                                USING ERRCODE = 'check_violation', CONSTRAINT = 'trg_tasks_br3_assignee_active';
                        END IF;
                    ELSIF OLD.status IN ('Completed', 'Cancelled') AND NEW.status IS DISTINCT FROM OLD.status THEN
                        -- BR4: Completed and Cancelled are final.
                        RAISE EXCEPTION 'BR4: task % is %; Completed and Cancelled are final.', OLD.id, OLD.status
                            USING ERRCODE = 'check_violation', CONSTRAINT = 'trg_tasks_br4_final_status';
                    END IF;
                    RETURN NEW;
                END;
                $$;
                """);

            migrationBuilder.Sql("""
                CREATE TRIGGER trg_tasks_br3_br4
                    BEFORE INSERT OR UPDATE OF status ON tasks
                    FOR EACH ROW EXECUTE FUNCTION tasks_enforce_br3_br4();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TRIGGER IF EXISTS trg_tasks_br3_br4 ON tasks;");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS tasks_enforce_br3_br4();");

            migrationBuilder.DropTable(
                name: "tasks");

            migrationBuilder.DropTable(
                name: "employees");
        }
    }
}
