namespace TaskManagement.Domain;

/// <summary>
/// A person who creates tasks and is assigned tasks.
/// </summary>
public sealed class Employee
{
    /// <summary>The maximum length of <see cref="FullName"/>.</summary>
    public const int FullNameMaxLength = 200;

    /// <summary>The maximum length of <see cref="Email"/>.</summary>
    public const int EmailMaxLength = 254;

    private Employee()
    {
        FullName = string.Empty;
        Email = string.Empty;
    }

    /// <summary>Gets the identifier, generated by <see cref="Create"/>.</summary>
    public Guid Id { get; private set; }

    /// <summary>Gets the trimmed full name (1..<see cref="FullNameMaxLength"/> characters).</summary>
    public string FullName { get; private set; }

    /// <summary>Gets the trimmed, lower-invariant email address (1..<see cref="EmailMaxLength"/> characters).</summary>
    public string Email { get; private set; }

    /// <summary>Gets a value indicating whether the employee can be given a new task.</summary>
    /// <remarks>Enforces BR3: an inactive employee cannot be assigned a new task; see <see cref="TaskItem.Create"/>.</remarks>
    public bool IsActive { get; private set; }

    /// <summary>
    /// Creates a new, active employee.
    /// </summary>
    /// <param name="fullName">The employee's full name.</param>
    /// <param name="email">The employee's email address.</param>
    /// <returns>A new, active <see cref="Employee"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="fullName"/> or <paramref name="email"/> is null.</exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="fullName"/> or <paramref name="email"/> is empty, whitespace, or longer than the allowed
    /// maximum once trimmed.
    /// </exception>
    public static Employee Create(string fullName, string email)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(fullName);
        var trimmedFullName = fullName.Trim();
        if (trimmedFullName.Length > FullNameMaxLength)
        {
            throw new ArgumentException("Full name cannot be longer than 200 characters.", nameof(fullName));
        }

        ArgumentException.ThrowIfNullOrWhiteSpace(email);
        var normalisedEmail = email.Trim().ToLowerInvariant();
        if (normalisedEmail.Length > EmailMaxLength)
        {
            throw new ArgumentException("Email cannot be longer than 254 characters.", nameof(email));
        }

        return new Employee
        {
            Id = Guid.CreateVersion7(),
            FullName = trimmedFullName,
            Email = normalisedEmail,
            IsActive = true,
        };
    }

    /// <summary>
    /// Marks the employee as unable to receive new tasks.
    /// </summary>
    /// <remarks>
    /// Enforces BR3. Idempotent: calling it on an already-inactive employee has no effect. Tasks the employee
    /// already has are unaffected.
    /// </remarks>
    public void Deactivate()
    {
        IsActive = false;
    }
}
