using System.Collections.Frozen;

namespace TaskManagement.Domain;

/// <summary>
/// A unit of work created by one employee and assigned to another.
/// </summary>
public sealed class TaskItem
{
    /// <summary>The maximum length of <see cref="Title"/>.</summary>
    public const int TitleMaxLength = 200;

    private static readonly FrozenDictionary<TaskItemStatus, FrozenSet<TaskItemStatus>> AllowedTransitions =
        new Dictionary<TaskItemStatus, HashSet<TaskItemStatus>>
        {
            [TaskItemStatus.New] = [TaskItemStatus.New, TaskItemStatus.InProgress, TaskItemStatus.Completed, TaskItemStatus.Cancelled],
            [TaskItemStatus.InProgress] = [TaskItemStatus.New, TaskItemStatus.InProgress, TaskItemStatus.Completed, TaskItemStatus.Cancelled],
            [TaskItemStatus.Completed] = [],
            [TaskItemStatus.Cancelled] = []
        }.ToFrozenDictionary(k => k.Key, v => v.Value.ToFrozenSet());

    private TaskItem()
    {
        Title = string.Empty;
    }

    /// <summary>Gets the identifier, generated by <see cref="Create"/>.</summary>
    public Guid Id { get; private set; }

    /// <summary>Gets the trimmed title (1..<see cref="TitleMaxLength"/> characters).</summary>
    public string Title { get; private set; }

    /// <summary>Gets the current status. <see cref="TaskItemStatus.New"/> after <see cref="Create"/>.</summary>
    public TaskItemStatus Status { get; private set; }

    /// <summary>Gets the identifier of the employee who created the task. Never changes.</summary>
    public Guid CreatorId { get; private set; }

    /// <summary>Gets the identifier of the employee the task is assigned to. Never changes.</summary>
    /// <remarks>Enforces BR5: set from <see cref="Employee.Id"/> of an assignee distinct from the creator.</remarks>
    public Guid AssigneeId { get; private set; }

    /// <summary>Gets the planned start date and time, in UTC, or null if not planned.</summary>
    public DateTimeOffset? PlannedStartAt { get; private set; }

    /// <summary>Gets the deadline, in UTC, or null if none.</summary>
    /// <remarks>Enforces BR2: when both this and <see cref="PlannedStartAt"/> are set, this is not earlier.</remarks>
    public DateTimeOffset? DueAt { get; private set; }

    /// <summary>Gets the completion date and time, in UTC.</summary>
    /// <remarks>Enforces BR1 (structural): non-null if and only if <see cref="Status"/> is <see cref="TaskItemStatus.Completed"/>.</remarks>
    public DateTimeOffset? CompletedAt { get; private set; }

    /// <summary>Gets the concurrency token, mapped to the PostgreSQL <c>xmin</c> system column. Never written by the domain.</summary>
    public uint Version { get; private set; }

    /// <summary>
    /// Creates a new task in status <see cref="TaskItemStatus.New"/>.
    /// </summary>
    /// <param name="title">The task title.</param>
    /// <param name="creator">The employee creating the task.</param>
    /// <param name="assignee">The employee the task is assigned to.</param>
    /// <param name="plannedStartAt">The planned start date and time, or null. Stored as the same instant in UTC (<c>ToUniversalTime()</c>).</param>
    /// <param name="dueAt">The deadline, or null. Stored as the same instant in UTC (<c>ToUniversalTime()</c>).</param>
    /// <returns>A new <see cref="TaskItem"/> with status <see cref="TaskItemStatus.New"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="title"/>, <paramref name="creator"/> or <paramref name="assignee"/> is null.</exception>
    /// <exception cref="ArgumentException"><paramref name="title"/> is empty, whitespace, or longer than 200 characters once trimmed.</exception>
    /// <exception cref="BusinessRuleViolationException">
    /// BR5: <paramref name="creator"/> and <paramref name="assignee"/> are the same employee. BR3:
    /// <paramref name="assignee"/> is inactive. BR2: both dates are set and <paramref name="dueAt"/> is earlier
    /// than <paramref name="plannedStartAt"/>.
    /// </exception>
    /// <remarks>
    /// Enforces BR5 (the creator is not the assignee), BR3 (the assignee is active) and BR2 (<c>DueAt</c> is not
    /// earlier than <c>PlannedStartAt</c>). The guards run in that order (spec &#167;3.2), and only the first violated
    /// rule is reported.
    /// </remarks>
    public static TaskItem Create(
        string title,
        Employee creator,
        Employee assignee,
        DateTimeOffset? plannedStartAt,
        DateTimeOffset? dueAt)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        var trimmedTitle = title.Trim();
        if (trimmedTitle.Length > TitleMaxLength)
        {
            throw new ArgumentException("Title cannot be longer than 200 characters.", nameof(title));
        }

        ArgumentNullException.ThrowIfNull(creator);
        ArgumentNullException.ThrowIfNull(assignee);

        var normalisedPlannedStartAt = plannedStartAt?.ToUniversalTime();
        var normalisedDueAt = dueAt?.ToUniversalTime();

        if (creator.Id == assignee.Id)
        {
            throw new BusinessRuleViolationException("BR5", "BR5: A task cannot be assigned to its creator.");
        }

        if (!assignee.IsActive)
        {
            throw new BusinessRuleViolationException(
                "BR3",
                $"BR3: Employee {assignee.Id} is inactive and cannot be given a new task.");
        }

        return normalisedPlannedStartAt is not null && normalisedDueAt is not null && normalisedDueAt < normalisedPlannedStartAt
            ? throw new BusinessRuleViolationException("BR2", "BR2: DueAt cannot be earlier than PlannedStartAt.")
            : new TaskItem
            {
                Id = Guid.CreateVersion7(),
                Title = trimmedTitle,
                Status = TaskItemStatus.New,
                CreatorId = creator.Id,
                AssigneeId = assignee.Id,
                PlannedStartAt = normalisedPlannedStartAt,
                DueAt = normalisedDueAt,
                CompletedAt = null,
            };
    }

    /// <summary>
    /// Moves the task to <paramref name="newStatus"/>.
    /// </summary>
    /// <param name="newStatus">The status to move to.</param>
    /// <param name="changedAt">The date and time of the change, stored in UTC (<c>ToUniversalTime()</c>) as <see cref="CompletedAt"/> when moving to <see cref="TaskItemStatus.Completed"/>.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="newStatus"/> is not a defined <see cref="TaskItemStatus"/> member.</exception>
    /// <exception cref="BusinessRuleViolationException">BR4: the current <see cref="Status"/> is <see cref="TaskItemStatus.Completed"/> or <see cref="TaskItemStatus.Cancelled"/>, which are final.</exception>
    /// <remarks>
    /// Enforces BR4 (guard) and BR1 (the status/<see cref="CompletedAt"/> assignment). Moving a non-final task to
    /// the status it already has does nothing. For a final task the BR4 guard runs first, so even
    /// <c>Completed → Completed</c> is rejected.
    /// </remarks>
    public void ChangeStatus(TaskItemStatus newStatus, DateTimeOffset changedAt)
    {
        if (!Enum.IsDefined(newStatus))
        {
            throw new ArgumentOutOfRangeException(nameof(newStatus), newStatus, "Unknown task status.");
        }

        if (!AllowedTransitions.TryGetValue(Status, out var allowed) || !allowed.Contains(newStatus))
        {
            throw new BusinessRuleViolationException(
                "BR4",
                $"BR4: Task {Id} is {Status}; Completed and Cancelled are final.");
        }

        if (newStatus == Status)
        {
            return;
        }

        Status = newStatus;
        CompletedAt = newStatus == TaskItemStatus.Completed ? changedAt.ToUniversalTime() : null;
    }
}
