using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TaskManagement.Domain;

namespace TaskManagement.Infrastructure.Configurations;

/// <summary>
/// Maps <see cref="Employee"/> to the table <c>employees</c> and seeds its three demo rows.
/// </summary>
/// <remarks>
/// <para>Creates:</para>
/// <list type="bullet">
/// <item><c>pk_employees</c>: primary key on <c>id</c> (<c>uuid</c>, generated by the domain, never by the database; ADR 0003).</item>
/// <item><c>ux_employees_email</c>: unique index on <c>email</c>. The domain lower-cases e-mails, so the index makes
/// e-mail uniqueness case-insensitive (ADR 0005).</item>
/// </list>
/// <para>
/// Seed: Alice Morgan and Bob Chen (active) and Carol Diaz (inactive). Carol exists so BR3 can be tested against
/// the database. No concurrency token: the only mutation (<see cref="Employee.Deactivate"/>) is idempotent.
/// </para>
/// </remarks>
public sealed class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
        builder.ToTable("employees");

        builder.HasKey(e => e.Id).HasName("pk_employees");
        builder.Property(e => e.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(e => e.FullName).HasColumnName("full_name").HasMaxLength(Employee.FullNameMaxLength).IsRequired();
        builder.Property(e => e.Email).HasColumnName("email").HasMaxLength(Employee.EmailMaxLength).IsRequired();
        builder.Property(e => e.IsActive).HasColumnName("is_active");

        builder.HasIndex(e => e.Email).IsUnique().HasDatabaseName("ux_employees_email");

        builder.HasData(
            new { Id = new Guid("10000000-0000-0000-0000-000000000001"), FullName = "Alice Morgan", Email = "alice.morgan@example.com", IsActive = true },
            new { Id = new Guid("10000000-0000-0000-0000-000000000002"), FullName = "Bob Chen", Email = "bob.chen@example.com", IsActive = true },
            new { Id = new Guid("10000000-0000-0000-0000-000000000003"), FullName = "Carol Diaz", Email = "carol.diaz@example.com", IsActive = false });
    }
}
