using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TaskManagement.Domain;

namespace TaskManagement.Infrastructure.Configurations;

/// <summary>
/// Maps <see cref="Employee"/> to the table <c>employees</c> and seeds its three demo rows.
/// </summary>
/// <remarks>
/// <para>Creates:</para>
/// <list type="bullet">
/// <item><c>pk_employees</c>: primary key on <c>id</c> (<c>uuid</c>, generated by the domain, never by the database; ADR 0003).</item>
/// <item><c>ux_employees_email</c>: unique index on <c>email</c>. The index itself compares exactly; e-mails written
/// through <see cref="Employee.Create"/> are lower-cased, which makes uniqueness case-insensitive for them. Raw SQL
/// can still insert a differently-cased duplicate (ADR 0005).</item>
/// </list>
/// <para>
/// Seed: Олена Коваленко and Богдан Шевченко (active) and Оксана Мельник (inactive). Оксана exists so BR3 can be tested against
/// the database. No concurrency token: the only mutation (<see cref="Employee.Deactivate"/>) is idempotent.
/// </para>
/// </remarks>
public sealed class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
        builder.ToTable("employees");

        builder.HasKey(e => e.Id).HasName("pk_employees");
        builder.Property(e => e.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(e => e.FullName).HasColumnName("full_name").HasMaxLength(Employee.FullNameMaxLength).IsRequired();
        builder.Property(e => e.Email).HasColumnName("email").HasMaxLength(Employee.EmailMaxLength).IsRequired();
        builder.Property(e => e.IsActive).HasColumnName("is_active");

        builder.HasIndex(e => e.Email).IsUnique().HasDatabaseName("ux_employees_email");

        builder.HasData(
            new { Id = new Guid("10000000-0000-0000-0000-000000000001"), FullName = "Олена Коваленко", Email = "olena.kovalenko@example.com", IsActive = true },
            new { Id = new Guid("10000000-0000-0000-0000-000000000002"), FullName = "Богдан Шевченко", Email = "bohdan.shevchenko@example.com", IsActive = true },
            new { Id = new Guid("10000000-0000-0000-0000-000000000003"), FullName = "Оксана Мельник", Email = "oksana.melnyk@example.com", IsActive = false });
    }
}
