using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TaskManagement.Domain;

namespace TaskManagement.Infrastructure.Configurations;

/// <summary>
/// Maps <see cref="TaskItem"/> to the table <c>tasks</c> and seeds its three demo rows.
/// </summary>
/// <remarks>
/// <para>Creates:</para>
/// <list type="bullet">
/// <item><c>pk_tasks</c>: primary key on <c>id</c> (<c>uuid</c>, generated by the domain; ADR 0003).</item>
/// <item><c>fk_tasks_employees_creator_id</c> and <c>fk_tasks_employees_assignee_id</c>: foreign keys to
/// <c>employees(id)</c>, <c>ON DELETE RESTRICT</c>. Employees are deactivated, not deleted; deleting one who still
/// has tasks must fail loudly instead of cascading away task history.</item>
/// <item><c>ix_tasks_assignee_id_status</c>: index on <c>(assignee_id, status)</c> (brief: assignee and status). Its
/// leading column also serves "list by assignee" and the assignee foreign key, so EF adds no separate index.</item>
/// <item><c>ix_tasks_due_at</c>: index on <c>due_at</c> (brief: due date).</item>
/// <item><c>ix_tasks_creator_id</c>: index on <c>creator_id</c> for the creator foreign key's <c>ON DELETE RESTRICT</c>
/// lookups; named so it is not EF's default <c>IX_…</c>.</item>
/// <item><c>ck_tasks_status_valid</c>: CHECK that <c>status</c> is one of the four <see cref="TaskItemStatus"/>
/// member names (status is stored as text, ADR 0007).</item>
/// <item><c>ck_tasks_br1_completed_at_iff_completed</c>: CHECK, enforces BR1 (<c>completed_at</c> is set iff status
/// is <c>Completed</c>).</item>
/// <item><c>ck_tasks_br2_due_at_not_before_planned_start_at</c>: CHECK, enforces BR2 (<c>due_at</c> not earlier than
/// <c>planned_start_at</c> when both are set).</item>
/// <item><c>ck_tasks_br5_assignee_not_creator</c>: CHECK, enforces BR5 (assignee differs from creator).</item>
/// </list>
/// <para>
/// BR3 (inactive assignee) and BR4 (final statuses) need another row or the previous value, which a CHECK cannot
/// see. They are enforced by the trigger <c>trg_tasks_br3_br4</c> (function <c>tasks_enforce_br3_br4()</c>), which
/// lives in the <c>InitialCreate</c> migration as raw SQL, not in this model (ADR 0009).
/// </para>
/// <para>
/// <see cref="TaskItem.Version"/> is the concurrency token, mapped by Npgsql's convention to the <c>xmin</c> system
/// column. It stops two concurrent status changes from both succeeding (protects BR4).
/// </para>
/// </remarks>
public sealed class TaskItemConfiguration : IEntityTypeConfiguration<TaskItem>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<TaskItem> builder)
    {
        builder.ToTable("tasks", t =>
        {
            t.HasCheckConstraint("ck_tasks_status_valid", "status IN ('New', 'InProgress', 'Completed', 'Cancelled')");
            t.HasCheckConstraint("ck_tasks_br1_completed_at_iff_completed", "(status = 'Completed' AND completed_at IS NOT NULL) OR (status <> 'Completed' AND completed_at IS NULL)");
            t.HasCheckConstraint("ck_tasks_br2_due_at_not_before_planned_start_at", "planned_start_at IS NULL OR due_at IS NULL OR due_at >= planned_start_at");
            t.HasCheckConstraint("ck_tasks_br5_assignee_not_creator", "assignee_id <> creator_id");
        });

        builder.HasKey(t => t.Id).HasName("pk_tasks");
        builder.Property(t => t.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(t => t.Title).HasColumnName("title").HasMaxLength(TaskItem.TitleMaxLength).IsRequired();
        builder.Property(t => t.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(20);
        builder.Property(t => t.CreatorId).HasColumnName("creator_id");
        builder.Property(t => t.AssigneeId).HasColumnName("assignee_id");
        builder.Property(t => t.PlannedStartAt).HasColumnName("planned_start_at");
        builder.Property(t => t.DueAt).HasColumnName("due_at");
        builder.Property(t => t.CompletedAt).HasColumnName("completed_at");
        builder.Property(t => t.Version).IsRowVersion();

        builder.HasOne<Employee>().WithMany().HasForeignKey(t => t.CreatorId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_tasks_employees_creator_id");
        builder.HasOne<Employee>().WithMany().HasForeignKey(t => t.AssigneeId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_tasks_employees_assignee_id");

        builder.HasIndex(t => new { t.AssigneeId, t.Status }).HasDatabaseName("ix_tasks_assignee_id_status");
        builder.HasIndex(t => t.DueAt).HasDatabaseName("ix_tasks_due_at");
        builder.HasIndex(t => t.CreatorId).HasDatabaseName("ix_tasks_creator_id");

        var alice = new Guid("10000000-0000-0000-0000-000000000001");
        var bob = new Guid("10000000-0000-0000-0000-000000000002");
        builder.HasData(
            new
            {
                Id = new Guid("20000000-0000-0000-0000-000000000001"),
                Title = "Prepare Q4 sales report",
                Status = TaskItemStatus.New,
                CreatorId = alice,
                AssigneeId = bob,
                PlannedStartAt = (DateTimeOffset?)new DateTimeOffset(2026, 10, 1, 9, 0, 0, TimeSpan.Zero),
                DueAt = (DateTimeOffset?)new DateTimeOffset(2026, 10, 10, 17, 0, 0, TimeSpan.Zero),
                CompletedAt = (DateTimeOffset?)null,
            },
            new
            {
                Id = new Guid("20000000-0000-0000-0000-000000000002"),
                Title = "Call back key account",
                Status = TaskItemStatus.Completed,
                CreatorId = bob,
                AssigneeId = alice,
                PlannedStartAt = (DateTimeOffset?)new DateTimeOffset(2026, 9, 1, 9, 0, 0, TimeSpan.Zero),
                DueAt = (DateTimeOffset?)new DateTimeOffset(2026, 9, 5, 17, 0, 0, TimeSpan.Zero),
                CompletedAt = (DateTimeOffset?)new DateTimeOffset(2026, 9, 4, 15, 30, 0, TimeSpan.Zero),
            },
            new
            {
                Id = new Guid("20000000-0000-0000-0000-000000000003"),
                Title = "Clean up duplicate contacts",
                Status = TaskItemStatus.Cancelled,
                CreatorId = alice,
                AssigneeId = bob,
                PlannedStartAt = (DateTimeOffset?)null,
                DueAt = (DateTimeOffset?)null,
                CompletedAt = (DateTimeOffset?)null,
            });
    }
}
